name: Mobile Build and Push

on:
  push:
    branches:
      - production
      - staging
    paths:
      - 'projects/apps/mobile/**'

env:
  GITHUB_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  SHA: ${{ github.event.after }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.GITHUB_REGISTRY }}/${{ env.IMAGE_NAME }}/mobile
          labels: org.opencontainers.image.revision=${{ env.SHA }}
          tags: |
            type=raw,value=latest,enable=true
            type=sha,prefix=,suffix=,format=short

      - name: Set Build Args
        run: |
          value=$(echo "${{ github.event.ref }}" | cut -d'/' -f3)
          echo "BUILD_ENV=${value}" >> $GITHUB_ENV

      - name: Build Docker image for MOBILE
        id: build_mobile
        uses: docker/build-push-action@v5
        with:
          context: .
          file: projects/apps/mobile/Dockerfile
          push: true
          platforms: ${{ matrix.platform }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Remove unused images
        run: |
          docker images --format "{{.ID}} {{.Tag}} {{.CreatedAt}}" | sort -k 3 -r | awk '{if (NR > 1 && NR > 6) print $1}' | xargs -r docker rmi -f
          docker image prune -f
